default_agent: echoGray_Agent
agents:
  echoGray_Agent:
    name: echoGray_Agent
    entrypoint: /Users/yuval/Documents/work/_examples/aws-examples/bedrock-agentcore/echoGray/src/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: /Users/yuval/Documents/work/_examples/aws-examples/bedrock-agentcore/echoGray/src
    aws:
      execution_role: arn:aws:iam::240378375036:role/AmazonBedrockAgentCoreSDKRuntime-eu-central-1-5c902ba6b5
      execution_role_auto_create: false
      account: '240378375036'
      region: eu-central-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-240378375036-eu-central-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: echoGray_Agent-iQ6fKY8p24
      agent_arn: arn:aws:bedrock-agentcore:eu-central-1:240378375036:runtime/echoGray_Agent-iQ6fKY8p24
      agent_session_id: 8d0ff2d5-840d-4067-b57b-ae2d9ea6be7d
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: OPENAI_API_KEY
    api_key_credential_provider_name: echogray_agent_openai_api_key
    is_generated_by_agentcore_create: true
